# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Lints the podspec"
  lane :lint_podspec do |opts|
    set_pod_version(opts[tag])
    sh("pod lib lint ../../SwiftyTesseract.podspec")
  end

  desc "Lints and pushes podspec to Cocoapods trunk"
  lane :deploy_to_cocoapods do |opts|
    set_pod_version(opts[:tag])
    sh("pod spec lint ../../")
    sh("pod trunk push ../../SwiftyTesseract.podspec")
  end

  def set_pod_version(tag)
    ENV["POD_VERSION"] = tag
    puts("set pod version to #{ENV["POD_VERSION"]}")
  end
end
